// Traditional Chinese descriptions for every scoring element. Keys mirror
// HK_FANS / MCR_FANS; TypeScript makes sure none are missing.

import type { HkFan } from './hk';
import type { McrFan } from './mcr';

export const HK_DESC_ZH: Record<HkFan, string> = {
  selfPick: '和牌的那張是自己從牌牆摸回來的。',
  kongReplacement: '開槓後補回來的牌令你和牌（取代自摸）。',
  doubleKongReplacement: '連續開兩次槓，用第二張補牌和牌（取代自摸）。',
  concealedHand: '沒有上、碰或明槓過任何牌。',
  robbingKong: '別人加槓的那張牌正是你要的，搶槓和牌。',
  moonUnderSea: '用牌牆最後一張牌或最後一張打出的牌和牌。',
  dragon: '一組三元牌（中、發、白）刻子，每組 1 番。',
  smallThreeDragons: '兩組三元牌刻子，加第三種三元牌做眼。',
  bigThreeDragons: '中、發、白三組刻子齊全。',
  seatWind: '有自己門風的刻子。',
  roundWind: '有圈風的刻子。',
  smallFourWinds: '三組風牌刻子，加第四種風牌做眼。',
  bigFourWinds: '東、南、西、北四組刻子齊全。',
  mixedFlush: '只有一種花色加字牌。',
  fullFlush: '全副牌只有一種花色，沒有字牌。',
  allSequences: '四組都是順子。',
  allTriplets: '四組都是刻子或槓。',
  allConcealedTriplets: '四組刻子全是自己摸齊的；打出的牌只可以用來做眼。',
  mixedTerminals: '只有一、九及字牌（已包括對對糊的 3 番）。',
  allHonours: '全副都是字牌（已包括對對糊的 3 番）。',
  allTerminals: '只有一和九（已包括對對糊的 3 番）。',
  allQuadruplets: '四組都是槓。',
  noFlowers: '沒有花也沒有季。',
  seatFlower: '每隻與自己座位號碼相同的花或季，各 1 番。',
  fullFlowerSet: '四隻花或四隻季齊全。',
  sevenFlowers: '摸到第七隻花即可宣佈和牌。',
  eightFlowers: '八隻花季全部到手。',
  heavenly: '莊家開牌即和。',
  earthly: '閒家用莊家打出的第一張牌和牌。',
  humanly: '閒家第一次摸牌就自摸和牌。',
  nineGates: '同一花色 1112345678999，再加任何一張同花色的牌。',
  thirteenOrphans: '一、九、東南西北中發白各一張，再加其中一張成對。',
  sevenPairs: '七對不同的對子。',
};

export const MCR_DESC_ZH: Record<McrFan, string> = {
  bigFourWinds: '東南西北四組風刻（或槓）。',
  bigThreeDragons: '中發白三組箭刻（或槓）。',
  allGreen: '只由二、三、四、六、八條及發財組成。',
  nineGates: '同一花色 1112345678999 聽一至九任何一張。',
  fourKongs: '四組槓。',
  sevenShiftedPairs: '同一花色七對相連的對子。',
  thirteenOrphans: '么九牌及字牌各一張，再加其中一張成對。',
  allTerminals: '只有一和九，沒有字牌。',
  littleFourWinds: '三組風刻，加第四種風牌做將。',
  littleThreeDragons: '兩組箭刻，加第三種箭牌做將。',
  allHonors: '全副都是字牌。',
  fourConcealedPungs: '四組刻子（或槓）全部自己摸齊。',
  pureTerminalChows: '同一花色兩組一二三、兩組七八九，加同花色五做將。',
  quadrupleChow: '同一花色四組完全相同的順子。',
  fourPureShiftedPungs: '同一花色四組遞增一的刻子。',
  fourPureShiftedChows: '同一花色四組順子，每組遞增一（或每組遞增二）。',
  threeKongs: '三組槓。',
  allTermHonors: '只有一、九及字牌。',
  sevenPairs: '七個對子。',
  greaterHonorsKnitted: '七種字牌各一張，加組合龍（147、258、369 分屬三種花色）的單張。',
  allEvenPungs: '刻子和將全是二、四、六、八。',
  fullFlush: '全副牌只有一種花色。',
  pureTripleChow: '同一花色三組完全相同的順子。',
  pureShiftedPungs: '同一花色三組遞增一的刻子。',
  upperTiles: '只有七、八、九。',
  middleTiles: '只有四、五、六。',
  lowerTiles: '只有一、二、三。',
  pureStraight: '同一花色一二三、四五六、七八九。',
  threeSuitedTerminalChows: '兩種花色各有一二三及七八九，第三種花色五做將。',
  pureShiftedChows: '同一花色三組順子，每組遞增一（或每組遞增二）。',
  allFives: '每組及將都有五。',
  triplePung: '三種花色同一數字的刻子。',
  threeConcealedPungs: '三組刻子（或槓）自己摸齊。',
  lesserHonorsKnitted: '十四張互不相連的單張：字牌加組合龍的牌。',
  knittedStraight: '147、258、369 分屬三種不同花色。',
  upperFour: '只有六、七、八、九。',
  lowerFour: '只有一、二、三、四。',
  bigThreeWinds: '三組風刻。',
  mixedStraight: '一二三、四五六、七八九分屬三種不同花色。',
  reversibleTiles: '只用倒轉看也一樣的牌（一二三四五八九筒、二四五六八九條、白板）。',
  mixedTripleChow: '三種花色同一數字的順子。',
  mixedShiftedPungs: '三種花色的刻子，數字各遞增一。',
  chickenHand: '除花牌外沒有其他番種。',
  lastTileDraw: '摸牌牆最後一張牌自摸和牌。',
  lastTileClaim: '和全局最後一張打出的牌。',
  outWithReplacement: '開槓後補回的牌和牌。',
  robbingKong: '和別人加槓的那張牌。',
  twoConcealedKongs: '兩組暗槓。',
  allPungs: '四組刻子（或槓）加一對將。',
  halfFlush: '一種花色加字牌。',
  mixedShiftedChows: '三種花色的順子，每組遞增一。',
  allTypes: '萬、筒、條、風、箭五門齊全。',
  meldedHand: '四組全部吃碰回來，再單釣別人打出的牌做將。',
  twoDragonPungs: '兩組箭刻。',
  meldedConcealedKongs: '一組明槓加一組暗槓。',
  outsideHand: '每組及將都帶么九或字牌。',
  fullyConcealed: '沒有吃碰明槓，並且自摸和牌。',
  twoMeldedKongs: '兩組明槓。',
  lastTile: '和的是場上最後一張（其餘三張已現）。',
  dragonPung: '一組箭刻（中、發、白）。',
  prevalentWind: '圈風的刻子。',
  seatWind: '自己門風的刻子。',
  concealedHand: '沒有吃碰明槓，和別人打出的牌。',
  allChows: '四組順子，將不是字牌。',
  tileHog: '同一張牌四張都用上，但不是槓。',
  doublePung: '兩種花色同一數字的刻子。',
  twoConcealedPungs: '兩組刻子（或槓）自己摸齊。',
  concealedKong: '一組暗槓。',
  allSimples: '沒有么九及字牌。',
  pureDoubleChow: '同一花色兩組相同的順子。',
  mixedDoubleChow: '兩種花色同一數字的順子。',
  shortStraight: '同一花色兩組相連成六張的順子。',
  twoTerminalChows: '同一花色的一二三及七八九。',
  pungTermHonor: '一或九的刻子，或不計分的風刻。',
  meldedKong: '一組明槓。',
  oneVoidedSuit: '缺少萬、筒、條其中一門。',
  noHonors: '沒有風牌和箭牌。',
  edgeWait: '只聽一二三的三，或七八九的七。',
  closedWait: '只聽順子中間的一張。',
  singleWait: '只聽做將的一張。',
  selfDrawn: '自己摸牌和牌。',
  flowerTiles: '每隻花季 1 分（不計入 8 分起和）。',
};
